####################################################
# DVrouter.py
# Name:
# HUID:
#####################################################

import json

from router import Router
from packet import Packet

class DVrouter(Router):
    """Distance vector routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    INFINITY = 1000

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here

        self.neighbor_distances = { # bảng khoảng cách đến các router lân cận indexed by neighbor address
            self.addr: {
                "port": None,
                "distance": 0       # khoảng cách tới chính mình là 0
            }
        }

        self.forwarding_table = { # bảng định tuyến indexed by dest address
            self.addr: {
                "next hop": self.addr,
                "port": None,
                "distance": 0
            }
        }

        self.neighbor_tables = {} # bảng định tuyến của hàng xóm indexed by neighbor address

        self.ports = {}     # port indexed by neighbor
        self.neighbors = {} # neighbor indexed by port

    def broadcast(self):
        for port in self.links:
            # chỉ gửi cho router, không gửi cho client
            if 'A' <= self.neighbors[port] and self.neighbors[port] <= 'Z':
                packet = Packet(Packet.ROUTING, self.addr, None, json.dumps(self.forwarding_table))
                self.send(port, packet)

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            if packet.dst_addr in self.forwarding_table and self.forwarding_table[packet.dst_addr]["distance"] < self.INFINITY:
                self.send(self.forwarding_table[packet.dst_addr]["port"], packet)
                    
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the received distance vector is different
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
            #   broadcast the distance vector of this router to neighbors

            neighbor = packet.src_addr
            neighbor_table = json.loads(packet.content)
            self.neighbor_tables[neighbor] = neighbor_table  # add bảng định tuyến của hàng xóm này
            is_changed = False

            # kiểm tra xem có tìm được đường ngắn hơn đến các điểm không
            for dst in neighbor_table:

                # Nếu khoảng cách từ hàng xóm đến dst nào đó = INFINITY và mình đi đến dst qua hàng xóm => mình đi đến dst = INFINITY
                if dst in self.forwarding_table and neighbor_table[dst]["distance"] == self.INFINITY and self.forwarding_table[dst]["next hop"] == neighbor:
                    self.forwarding_table[dst]["distance"] = self.INFINITY
                    is_changed = True

                # Nếu AB + B->C < A->C (hoặc là chưa có A->C)  => A->C = AB + B->C (cập nhật khoảng cách)
                elif not(dst in self.forwarding_table) or self.neighbor_distances[neighbor]["distance"] + neighbor_table[dst]["distance"] < self.forwarding_table[dst]["distance"]:
                    self.forwarding_table[dst] = {
                        "next hop": neighbor,
                        "port": port,
                        "distance": self.neighbor_distances[neighbor]["distance"] + neighbor_table[dst]["distance"]
                    }
                    is_changed = True


            # nếu thay đổi bảng định tuyến thì thông báo cho router lân cận
            if is_changed:
                self.broadcast()

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors


        self.ports[endpoint] = port
        self.neighbors[port] = endpoint

        # add khoảng cách đến router mới vào bảng
        self.neighbor_distances[endpoint] = {
            "port": port,
            "distance": cost
        }

        is_changed = False

        # nếu chưa có hoặc đường trực tiếp đến endpoint này ngắn hơn đường cũ => forwarding là endpoint luôn
        if not(endpoint in self.forwarding_table) or (endpoint in self.forwarding_table and cost < self.forwarding_table[endpoint]["distance"]):
            self.forwarding_table[endpoint] = {
                "next hop": endpoint,
                "port": port,
                "distance": cost
            }
            is_changed = True

        # gửi bảng định tuyến cho các router lân cận
        if is_changed:
            self.broadcast()

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors


        neighbor = self.neighbors[port]
        del self.ports[neighbor]
        del self.neighbors[port]

        del self.neighbor_distances[neighbor]   # xóa khoảng cách trực tiếp đến neighbor
        del self.neighbor_tables[neighbor]      # xóa bảng định tuyến của neighbor đó

        # nếu đến dst nào mà cần đi qua neighbor bị gỡ => khoảng cách = INFINITY
        for dst in self.forwarding_table:
            if self.forwarding_table[dst]["next hop"] == neighbor:
                self.forwarding_table[dst]["distance"] = self.INFINITY
        
        self.broadcast()
            

    def handle_time(self, time_ms):
        """Handle current time."""
        
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the distance vector of this router to neighbors

            # gửi bảng định tuyến định kỳ cho router lân cận
            self.broadcast()

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"DVrouter(addr={self.addr})"